### ISSUE TITLE
Remove .idea and other cache files

### ISSUE THREAD

**Issue by tianshanghong** [shenzheyu/LeetCode#1]
I see many temporary files in the project. These files are not useful and may mislead others. Strongly suggest remove these files from the project.

**Comment by shenzheyu** [comment]
I am sincerely apologize for the inconvenience.  It leads to the problem that I just follow the .gitignore role in https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore. These additional configuration files make sure for you to compile and run the project in IntelliJ IDEA successfully. I really appreciate your issue to make this project better.
